import {
  CUSTOM_SHADER_ENTRY_EXPORT,
  CUSTOM_SHADER_INTERNAL_VISIBILITY,
  CUSTOM_SHADER_STARTER,
} from "@/features/editor/custom-shader/shared"
import type {
  EffectLayerType,
  LayerDefinition,
  LayerKind,
  LayerType,
  ModelLayerType,
  ParameterDefinitions,
  SourceLayerType,
} from "@/features/editor/types"

const imageParams = [
  {
    defaultValue: "cover",
    key: "fitMode",
    label: "Fit",
    options: [
      { label: "Cover", value: "cover" },
      { label: "Contain", value: "contain" },
      { label: "Stretch", value: "stretch" },
    ],
    type: "select",
  },
  {
    defaultValue: 1,
    key: "scale",
    label: "Scale",
    max: 4,
    min: 0.25,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: [0, 0] as [number, number],
    key: "offset",
    label: "Offset",
    max: 1,
    min: -1,
    step: 0.01,
    type: "vec2",
  },
] as const satisfies ParameterDefinitions

const videoParams = [
  ...imageParams,
  {
    defaultValue: 1,
    key: "playbackRate",
    label: "Playback Rate",
    max: 4,
    min: 0.25,
    step: 0.05,
    type: "number",
  },
] as const satisfies ParameterDefinitions

const liveParams = [
  {
    defaultValue: "user",
    key: "facingMode",
    label: "Camera",
    options: [
      { label: "Front", value: "user" },
      { label: "Back", value: "environment" },
    ],
    type: "select",
  },
  {
    defaultValue: true,
    key: "mirror",
    label: "Mirror",
    type: "boolean",
  },
  {
    defaultValue: "cover",
    key: "fitMode",
    label: "Fit",
    options: [
      { label: "Cover", value: "cover" },
      { label: "Contain", value: "contain" },
      { label: "Stretch", value: "stretch" },
    ],
    type: "select",
  },
  {
    defaultValue: 1,
    key: "scale",
    label: "Scale",
    max: 4,
    min: 0.25,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: [0, 0] as [number, number],
    key: "offset",
    label: "Offset",
    max: 1,
    min: -1,
    step: 0.01,
    type: "vec2",
  },
] as const satisfies ParameterDefinitions

const customShaderParams = [
  {
    animatable: false,
    defaultValue: "paste",
    key: "sourceMode",
    label: "Source Mode",
    options: [
      { label: "Paste", value: "paste" },
      { label: "File", value: "file" },
    ],
    type: "select",
    visibleWhen: CUSTOM_SHADER_INTERNAL_VISIBILITY,
  },
  {
    animatable: false,
    defaultValue: CUSTOM_SHADER_STARTER,
    key: "sourceCode",
    label: "Source Code",
    type: "text",
    visibleWhen: CUSTOM_SHADER_INTERNAL_VISIBILITY,
  },
  {
    animatable: false,
    defaultValue: "",
    key: "sourceFileName",
    label: "Source File",
    type: "text",
    visibleWhen: CUSTOM_SHADER_INTERNAL_VISIBILITY,
  },
  {
    animatable: false,
    defaultValue: CUSTOM_SHADER_ENTRY_EXPORT,
    key: "entryExport",
    label: "Entry Export",
    maxLength: 64,
    type: "text",
    visibleWhen: CUSTOM_SHADER_INTERNAL_VISIBILITY,
  },
  {
    animatable: false,
    defaultValue: 0,
    key: "sourceRevision",
    label: "Source Revision",
    max: Number.MAX_SAFE_INTEGER,
    min: 0,
    step: 1,
    type: "number",
    visibleWhen: CUSTOM_SHADER_INTERNAL_VISIBILITY,
  },
] as const satisfies ParameterDefinitions

const gradientParams = [
  {
    defaultValue: "custom",
    group: "Points",
    key: "preset",
    label: "Preset",
    options: [
      { label: "Custom", value: "custom" },
      { label: "Forest", value: "aurora" },
      { label: "Ember", value: "sunset" },
      { label: "Abyss", value: "deep-ocean" },
      { label: "Violet", value: "neon-glow" },
    ],
    type: "select",
  },
  {
    defaultValue: 3,
    group: "Points",
    key: "activePoints",
    label: "Active Points",
    max: 5,
    min: 2,
    step: 1,
    type: "number",
  },
  {
    defaultValue: "#0E0C0C",
    group: "Points",
    key: "point1Color",
    label: "Point 1 Color",
    type: "color",
  },
  {
    defaultValue: [-0.82, -0.62] as [number, number],
    group: "Points",
    key: "point1Position",
    label: "Point 1 Position",
    max: 1.5,
    min: -1.5,
    step: 0.01,
    type: "vec2",
  },
  {
    defaultValue: 0.42,
    group: "Points",
    key: "point1Weight",
    label: "Point 1 Weight",
    max: 3,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: "#C1FF00",
    group: "Points",
    key: "point2Color",
    label: "Point 2 Color",
    type: "color",
  },
  {
    defaultValue: [0.22, 0.72] as [number, number],
    group: "Points",
    key: "point2Position",
    label: "Point 2 Position",
    max: 1.5,
    min: -1.5,
    step: 0.01,
    type: "vec2",
  },
  {
    defaultValue: 1.55,
    group: "Points",
    key: "point2Weight",
    label: "Point 2 Weight",
    max: 3,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: "#B2DAD5",
    group: "Points",
    key: "point3Color",
    label: "Point 3 Color",
    type: "color",
    visibleWhen: {
      gte: 3,
      key: "activePoints",
    },
  },
  {
    defaultValue: [0.88, -0.26] as [number, number],
    group: "Points",
    key: "point3Position",
    label: "Point 3 Position",
    max: 1.5,
    min: -1.5,
    step: 0.01,
    type: "vec2",
    visibleWhen: {
      gte: 3,
      key: "activePoints",
    },
  },
  {
    defaultValue: 0.64,
    group: "Points",
    key: "point3Weight",
    label: "Point 3 Weight",
    max: 3,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      gte: 3,
      key: "activePoints",
    },
  },
  {
    defaultValue: "#3B4148",
    group: "Points",
    key: "point4Color",
    label: "Point 4 Color",
    type: "color",
    visibleWhen: {
      gte: 4,
      key: "activePoints",
    },
  },
  {
    defaultValue: [-0.34, 0.52] as [number, number],
    group: "Points",
    key: "point4Position",
    label: "Point 4 Position",
    max: 1.5,
    min: -1.5,
    step: 0.01,
    type: "vec2",
    visibleWhen: {
      gte: 4,
      key: "activePoints",
    },
  },
  {
    defaultValue: 0.82,
    group: "Points",
    key: "point4Weight",
    label: "Point 4 Weight",
    max: 3,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      gte: 4,
      key: "activePoints",
    },
  },
  {
    defaultValue: "#F3E7D0",
    group: "Points",
    key: "point5Color",
    label: "Point 5 Color",
    type: "color",
    visibleWhen: {
      gte: 5,
      key: "activePoints",
    },
  },
  {
    defaultValue: [0.58, -0.76] as [number, number],
    group: "Points",
    key: "point5Position",
    label: "Point 5 Position",
    max: 1.5,
    min: -1.5,
    step: 0.01,
    type: "vec2",
    visibleWhen: {
      gte: 5,
      key: "activePoints",
    },
  },
  {
    defaultValue: 0.48,
    group: "Points",
    key: "point5Weight",
    label: "Point 5 Weight",
    max: 3,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      gte: 5,
      key: "activePoints",
    },
  },
  {
    defaultValue: "simplex",
    group: "Distortion",
    key: "noiseType",
    label: "Noise",
    options: [
      { label: "Simplex", value: "simplex" },
      { label: "Turbulence", value: "turbulence" },
      { label: "Perlin", value: "perlin" },
    ],
    type: "select",
  },
  {
    defaultValue: 0.64,
    group: "Distortion",
    key: "warpAmount",
    label: "Warp Amount",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 5.56,
    group: "Distortion",
    key: "warpScale",
    label: "Warp Scale",
    max: 6,
    min: 0.1,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 1,
    group: "Distortion",
    key: "warpIterations",
    label: "Iterations",
    max: 5,
    min: 1,
    step: 1,
    type: "number",
  },
  {
    defaultValue: 1,
    group: "Distortion",
    key: "warpDecay",
    label: "Warp Decay",
    max: 3,
    min: 0.1,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.5,
    group: "Distortion",
    key: "warpBias",
    label: "Warp Bias",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.69,
    group: "Distortion",
    key: "vortexAmount",
    label: "Vortex",
    max: 1,
    min: -1,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: true,
    group: "Animation",
    key: "animate",
    label: "Animate",
    type: "boolean",
  },
  {
    defaultValue: 0,
    group: "Animation",
    key: "motionAmount",
    label: "Motion Amount",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.2,
    group: "Animation",
    key: "motionSpeed",
    label: "Motion Speed",
    max: 2,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "animate",
    },
  },
  {
    defaultValue: 2.05,
    group: "Distortion",
    key: "falloff",
    label: "Falloff",
    max: 4,
    min: 0.5,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: "reinhard",
    group: "Finish",
    key: "tonemapMode",
    label: "Tonemap",
    options: [
      { label: "None", value: "none" },
      { label: "ACES", value: "aces" },
      { label: "Reinhard", value: "reinhard" },
      { label: "Toto's", value: "totos" },
      { label: "Cinematic", value: "cinematic" },
    ],
    type: "select",
  },
  {
    defaultValue: 0,
    group: "Finish",
    key: "glowStrength",
    label: "Glow Strength",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0,
    group: "Finish",
    key: "glowThreshold",
    label: "Glow Threshold",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.08,
    group: "Finish",
    key: "grainAmount",
    label: "Grain",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.12,
    group: "Finish",
    key: "vignetteStrength",
    label: "Vignette Strength",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 1.5,
    group: "Finish",
    key: "vignetteRadius",
    label: "Vignette Radius",
    max: 1.5,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 1,
    group: "Finish",
    key: "vignetteSoftness",
    label: "Vignette Softness",
    max: 1,
    min: 0.01,
    step: 0.01,
    type: "number",
  },
] as const satisfies ParameterDefinitions

const fluidParams = [
  {
    defaultValue: 24,
    key: "iterations",
    label: "Iterations",
    max: 128,
    min: 4,
    step: 1,
    type: "number",
  },
  {
    defaultValue: 0.92,
    key: "dissipation",
    label: "Dissipation",
    max: 0.999,
    min: 0.5,
    step: 0.001,
    type: "number",
  },
  {
    defaultValue: 0.24,
    key: "pressure",
    label: "Pressure",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: "#3c73ff",
    key: "inkColor",
    label: "Ink Color",
    type: "color",
  },
] as const satisfies ParameterDefinitions

const modelParams = [
  {
    defaultValue: "studio",
    key: "environment",
    label: "Environment",
    options: [
      { label: "Studio", value: "studio" },
      { label: "Sunset", value: "sunset" },
      { label: "Warehouse", value: "warehouse" },
      { label: "Night", value: "night" },
    ],
    type: "select",
  },
  {
    defaultValue: 1,
    key: "environmentStrength",
    label: "Env Strength",
    max: 2,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 1.2,
    key: "cameraDistance",
    label: "Camera Distance",
    max: 6,
    min: 0.2,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: [0, 0, 0] as [number, number, number],
    key: "cameraOrbit",
    label: "Camera Orbit",
    max: 6.283,
    min: -6.283,
    step: 0.01,
    type: "vec3",
  },
  {
    defaultValue: false,
    key: "autoRotate",
    label: "Auto Rotate",
    type: "boolean",
  },
  {
    defaultValue: 0.6,
    key: "autoRotateSpeed",
    label: "Rotate Speed",
    max: 4,
    min: -4,
    step: 0.01,
    type: "number",
  },
] as const satisfies ParameterDefinitions

const asciiParams = [
  {
    defaultValue: 12,
    key: "cellSize",
    label: "Cell Size",
    max: 48,
    min: 4,
    step: 1,
    type: "number",
  },
  {
    animatable: false,
    defaultValue: "light",
    key: "charset",
    label: "Charset",
    options: [
      { label: "Light", value: "light" },
      { label: "Dense", value: "dense" },
      { label: "Blocks", value: "blocks" },
      { label: "Hatching", value: "hatching" },
      { label: "Binary", value: "binary" },
      { label: "Custom", value: "custom" },
    ],
    type: "select",
  },
  {
    animatable: false,
    defaultValue: " .:-=+*#%@",
    key: "customChars",
    label: "Custom Chars",
    maxLength: 32,
    type: "text",
    visibleWhen: {
      equals: "custom",
      key: "charset",
    },
  },
  {
    defaultValue: "regular",
    key: "fontWeight",
    label: "Font Weight",
    options: [
      { label: "Thin", value: "thin" },
      { label: "Regular", value: "regular" },
      { label: "Bold", value: "bold" },
    ],
    type: "select",
  },
  {
    defaultValue: "monochrome",
    key: "colorMode",
    label: "Color Mode",
    options: [
      { label: "Source", value: "source" },
      { label: "Monochrome", value: "monochrome" },
      // { label: "Green Terminal", value: "green-terminal" },
    ],
    type: "select",
  },
  {
    defaultValue: "#f5f5f0",
    key: "monoColor",
    label: "Tint",
    type: "color",
    visibleWhen: {
      equals: "monochrome",
      key: "colorMode",
    },
  },
  {
    defaultValue: 0,
    key: "bgOpacity",
    label: "Background",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      equals: "source",
      key: "colorMode",
    },
  },
  {
    defaultValue: false,
    key: "invert",
    label: "Invert",
    type: "boolean",
  },
  {
    defaultValue: false,
    group: "Bloom",
    key: "bloomEnabled",
    label: "Bloom",
    type: "boolean",
  },
  {
    defaultValue: 1.25,
    group: "Bloom",
    key: "bloomIntensity",
    label: "Intensity",
    max: 8,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "bloomEnabled",
    },
  },
  {
    defaultValue: 0.6,
    group: "Bloom",
    key: "bloomThreshold",
    label: "Threshold",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "bloomEnabled",
    },
  },
  {
    defaultValue: 6,
    group: "Bloom",
    key: "bloomRadius",
    label: "Radius",
    max: 24,
    min: 0,
    step: 0.25,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "bloomEnabled",
    },
  },
  {
    defaultValue: 0.35,
    group: "Bloom",
    key: "bloomSoftness",
    label: "Softness",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "bloomEnabled",
    },
  },
] as const satisfies ParameterDefinitions

const ditheringParams = [
  {
    defaultValue: "custom",
    group: "Pattern",
    key: "preset",
    label: "Preset",
    options: [
      { label: "Custom", value: "custom" },
      { label: "Game Boy", value: "gameboy" },
    ],
    type: "select",
  },
  {
    defaultValue: "bayer-4x4",
    group: "Pattern",
    key: "algorithm",
    label: "Algorithm",
    options: [
      { label: "Bayer 2x2", value: "bayer-2x2" },
      { label: "Bayer 4x4", value: "bayer-4x4" },
      { label: "Bayer 8x8", value: "bayer-8x8" },
      { label: "Noise", value: "noise" },
    ],
    type: "select",
  },
  {
    defaultValue: "source",
    group: "Color",
    key: "colorMode",
    label: "Color Mode",
    options: [
      { label: "Monochrome", value: "monochrome" },
      { label: "Source Color", value: "source" },
      { label: "Duo Tone", value: "duo-tone" },
    ],
    type: "select",
  },
  {
    defaultValue: "#f5f5f0",
    group: "Color",
    key: "monoColor",
    label: "Color",
    type: "color",
    visibleWhen: {
      equals: "monochrome",
      key: "colorMode",
    },
  },
  {
    defaultValue: "#101010",
    group: "Color",
    key: "shadowColor",
    label: "Shadow",
    type: "color",
    visibleWhen: {
      equals: "duo-tone",
      key: "colorMode",
    },
  },
  {
    defaultValue: "#f5f2e8",
    group: "Color",
    key: "highlightColor",
    label: "Highlight",
    type: "color",
    visibleWhen: {
      equals: "duo-tone",
      key: "colorMode",
    },
  },
  {
    defaultValue: 1,
    group: "Pattern",
    key: "pixelSize",
    label: "Pixel Size",
    max: 24,
    min: 1,
    step: 1,
    type: "number",
  },
  {
    defaultValue: 0.5,
    group: "Pattern",
    key: "spread",
    label: "Strength",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 4,
    group: "Color",
    key: "levels",
    label: "Levels",
    max: 16,
    min: 2,
    step: 1,
    type: "number",
  },
  {
    defaultValue: 1,
    group: "Effects",
    key: "dotScale",
    label: "Dot Scale",
    max: 1,
    min: 0.1,
    step: 0.1,
    type: "number",
  },
  {
    defaultValue: false,
    group: "Effects",
    key: "animateDither",
    label: "Animate Dither",
    type: "boolean",
  },
  {
    defaultValue: 1,
    group: "Effects",
    key: "ditherSpeed",
    label: "Dither Speed",
    max: 3,
    min: 0,
    step: 0.5,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "animateDither",
    },
  },
  {
    defaultValue: false,
    group: "Effects",
    key: "chromaticSplit",
    label: "Chromatic Split",
    type: "boolean",
  },
] as const satisfies ParameterDefinitions

const halftoneParams = [
  {
    defaultValue: "cmyk",
    key: "colorMode",
    label: "Color Mode",
    options: [
      { label: "Source", value: "source" },
      { label: "Monochrome", value: "monochrome" },
      { label: "Duotone", value: "duotone" },
      { label: "Custom", value: "custom" },
      { label: "CMYK", value: "cmyk" },
    ],
    type: "select",
  },
  {
    defaultValue: "circle",
    key: "shape",
    label: "Shape",
    options: [
      { label: "Circle", value: "circle" },
      { label: "Square", value: "square" },
      { label: "Diamond", value: "diamond" },
      { label: "Line", value: "line" },
    ],
    type: "select",
  },
  {
    defaultValue: 5,
    key: "spacing",
    label: "Spacing",
    max: 48,
    min: 2,
    step: 1,
    type: "number",
  },
  {
    defaultValue: 1,
    key: "dotSize",
    label: "Dot Size",
    max: 3,
    min: 0.1,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0,
    key: "dotMin",
    label: "Dot Min",
    max: 0.5,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 28,
    key: "angle",
    label: "Angle",
    max: 360,
    min: 0,
    step: 1,
    type: "number",
  },
  {
    defaultValue: 1,
    key: "contrast",
    label: "Contrast",
    max: 2,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.25,
    key: "softness",
    label: "Softness",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0,
    key: "dotGain",
    label: "Dot Gain",
    description: "Simulates ink bleeding into paper fibers",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0,
    key: "dotMorph",
    label: "Dot Morph",
    description:
      "Blends dot shape based on tonal value (circles → squares in midtones)",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: false,
    key: "invertLuma",
    label: "Invert",
    type: "boolean",
  },
  {
    defaultValue: 4,
    description: "Palette is distributed evenly across luminance bands.",
    key: "customColorCount",
    label: "Color Count",
    max: 4,
    min: 2,
    step: 1,
    type: "number",
    visibleWhen: { equals: "custom", key: "colorMode" },
  },
  {
    defaultValue: 0,
    description: "Shifts palette mapping toward shadows or highlights.",
    key: "customLuminanceBias",
    label: "Luminance Bias",
    max: 1,
    min: -1,
    step: 0.01,
    type: "number",
    visibleWhen: { equals: "custom", key: "colorMode" },
  },
  {
    defaultValue: false,
    group: "Bloom",
    key: "bloomEnabled",
    label: "Bloom",
    type: "boolean",
    visibleWhen: { equals: "custom", key: "colorMode" },
  },
  {
    defaultValue: 1.25,
    group: "Bloom",
    key: "bloomIntensity",
    label: "Intensity",
    max: 8,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: { equals: true, key: "bloomEnabled" },
  },
  {
    defaultValue: 0.6,
    group: "Bloom",
    key: "bloomThreshold",
    label: "Threshold",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: { equals: true, key: "bloomEnabled" },
  },
  {
    defaultValue: 6,
    group: "Bloom",
    key: "bloomRadius",
    label: "Radius",
    max: 24,
    min: 0,
    step: 0.25,
    type: "number",
    visibleWhen: { equals: true, key: "bloomEnabled" },
  },
  {
    defaultValue: 0.35,
    group: "Bloom",
    key: "bloomSoftness",
    label: "Softness",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: { equals: true, key: "bloomEnabled" },
  },
  {
    defaultValue: "#F5F5F0",
    key: "customBgColor",
    label: "Background",
    type: "color",
    visibleWhen: { equals: "custom", key: "colorMode" },
  },
  {
    defaultValue: "#0d1014",
    key: "customColor1",
    label: "Shadows",
    type: "color",
    visibleWhen: { equals: "custom", key: "colorMode" },
  },
  {
    defaultValue: "#4d5057",
    key: "customColor2",
    label: "Midtones / Highlights",
    type: "color",
    visibleWhen: { equals: "custom", key: "colorMode" },
  },
  {
    defaultValue: "#969aa2",
    key: "customColor3",
    label: "High Mids",
    type: "color",
    visibleWhen: {
      gte: 3,
      key: "customColorCount",
    },
  },
  {
    defaultValue: "#e1e2de",
    key: "customColor4",
    label: "Highlights",
    type: "color",
    visibleWhen: {
      gte: 4,
      key: "customColorCount",
    },
  },
  {
    defaultValue: "#0d1014",
    key: "ink",
    label: "Ink",
    type: "color",
    visibleWhen: { equals: "monochrome", key: "colorMode" },
  },
  {
    defaultValue: "#F5F5F0",
    key: "duotoneLight",
    label: "Light Color",
    type: "color",
    visibleWhen: { equals: "duotone", key: "colorMode" },
  },
  {
    defaultValue: "#1d1d1c",
    key: "duotoneDark",
    label: "Dark Color",
    type: "color",
    visibleWhen: { equals: "duotone", key: "colorMode" },
  },
  {
    defaultValue: "process",
    key: "preset",
    label: "Ink Preset",
    options: [
      { label: "Process CMYK", value: "process" },
      { label: "Risograph", value: "risograph" },
      { label: "Newspaper", value: "newspaper" },
      { label: "Vintage", value: "vintage" },
      { label: "Custom", value: "custom" },
    ],
    type: "select",
    visibleWhen: { equals: "cmyk", key: "colorMode" },
  },
  {
    defaultValue: 0.5,
    key: "gcr",
    label: "Black Generation",
    description: "Controls how much goes to the K plate vs C+M+Y",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: { equals: "cmyk", key: "colorMode" },
  },
  {
    defaultValue: "subtractive",
    key: "cmykBlend",
    label: "CMYK Blend",
    options: [
      { label: "Subtractive", value: "subtractive" },
      { label: "Overprint", value: "overprint" },
    ],
    type: "select",
    visibleWhen: { equals: "cmyk", key: "colorMode" },
  },
  {
    defaultValue: 15,
    key: "cyanAngle",
    label: "Cyan Angle",
    max: 90,
    min: 0,
    step: 1,
    type: "number",
    visibleWhen: { equals: "cmyk", key: "colorMode" },
  },
  {
    defaultValue: 75,
    key: "magentaAngle",
    label: "Magenta Angle",
    max: 90,
    min: 0,
    step: 1,
    type: "number",
    visibleWhen: { equals: "cmyk", key: "colorMode" },
  },
  {
    defaultValue: 0,
    key: "yellowAngle",
    label: "Yellow Angle",
    max: 90,
    min: 0,
    step: 1,
    type: "number",
    visibleWhen: { equals: "cmyk", key: "colorMode" },
  },
  {
    defaultValue: 45,
    key: "keyAngle",
    label: "Key Angle",
    max: 90,
    min: 0,
    step: 1,
    type: "number",
    visibleWhen: { equals: "cmyk", key: "colorMode" },
  },
  {
    defaultValue: "#F5F5F0",
    key: "paperColor",
    label: "Paper Color",
    type: "color",
    visibleWhen: { equals: "cmyk", key: "colorMode" },
  },
  {
    defaultValue: 0.15,
    key: "paperGrain",
    label: "Paper Grain",
    max: 0.5,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: { equals: "cmyk", key: "colorMode" },
  },
  {
    defaultValue: 0,
    key: "registration",
    label: "Registration",
    description: "Simulates plate misalignment in CMYK printing",
    max: 5,
    min: 0,
    step: 0.1,
    type: "number",
    visibleWhen: { equals: "cmyk", key: "colorMode" },
  },
  {
    defaultValue: "#00AEEF",
    key: "inkCyan",
    label: "Cyan Ink",
    type: "color",
    visibleWhen: { equals: "cmyk", key: "colorMode" },
  },
  {
    defaultValue: "#EC008C",
    key: "inkMagenta",
    label: "Magenta Ink",
    type: "color",
    visibleWhen: { equals: "cmyk", key: "colorMode" },
  },
  {
    defaultValue: "#FFF200",
    key: "inkYellow",
    label: "Yellow Ink",
    type: "color",
    visibleWhen: { equals: "cmyk", key: "colorMode" },
  },
  {
    defaultValue: "#1a1a1a",
    key: "inkKey",
    label: "Key Ink",
    type: "color",
    visibleWhen: { equals: "cmyk", key: "colorMode" },
  },
] as const satisfies ParameterDefinitions

const particleGridParams = [
  {
    defaultValue: 256,
    key: "gridResolution",
    label: "Resolution",
    max: 512,
    min: 32,
    step: 4,
    type: "number",
  },
  {
    defaultValue: 4,
    key: "pointSize",
    label: "Point Size",
    max: 32,
    min: 1,
    step: 1,
    type: "number",
  },
  {
    defaultValue: 0.1,
    key: "displacement",
    label: "Displacement",
    max: 2,
    min: -2,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: "#000000",
    key: "backgroundColor",
    label: "Background",
    type: "color",
  },
  {
    defaultValue: 0,
    group: "Motion",
    key: "noiseAmount",
    label: "Amount",
    max: 2,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 3,
    group: "Motion",
    key: "noiseScale",
    label: "Scale",
    max: 10,
    min: 0.5,
    step: 0.1,
    type: "number",
  },
  {
    defaultValue: 0.5,
    group: "Motion",
    key: "noiseSpeed",
    label: "Speed",
    max: 3,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: false,
    group: "Bloom",
    key: "bloomEnabled",
    label: "Bloom",
    type: "boolean",
  },
  {
    defaultValue: 1.25,
    group: "Bloom",
    key: "bloomIntensity",
    label: "Intensity",
    max: 8,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "bloomEnabled",
    },
  },
  {
    defaultValue: 0.6,
    group: "Bloom",
    key: "bloomThreshold",
    label: "Threshold",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "bloomEnabled",
    },
  },
  {
    defaultValue: 6,
    group: "Bloom",
    key: "bloomRadius",
    label: "Radius",
    max: 24,
    min: 0,
    step: 0.25,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "bloomEnabled",
    },
  },
  {
    defaultValue: 0.35,
    group: "Bloom",
    key: "bloomSoftness",
    label: "Softness",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "bloomEnabled",
    },
  },
] as const satisfies ParameterDefinitions

const pixelationParams = [
  {
    defaultValue: 8,
    key: "cellSize",
    label: "Cell Size",
    max: 64,
    min: 2,
    step: 1,
    type: "number",
  },
  {
    defaultValue: "square",
    key: "shape",
    label: "Shape",
    options: [
      { label: "Square", value: "square" },
      { label: "Circle", value: "circle" },
      { label: "Diamond", value: "diamond" },
    ],
    type: "select",
  },
] as const satisfies ParameterDefinitions

const pixelSortingParams = [
  {
    defaultValue: 0.25,
    key: "threshold",
    label: "Threshold",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 1,
    key: "upperThreshold",
    label: "Upper Threshold",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: "horizontal",
    key: "direction",
    label: "Direction",
    options: [
      { label: "Horizontal", value: "horizontal" },
      { label: "Vertical", value: "vertical" },
    ],
    type: "select",
  },
  {
    defaultValue: "luma",
    key: "mode",
    label: "Mode",
    options: [
      { label: "Luma", value: "luma" },
      { label: "Hue", value: "hue" },
      { label: "Saturation", value: "saturation" },
    ],
    type: "select",
  },
  {
    defaultValue: false,
    key: "reverse",
    label: "Reverse",
    type: "boolean",
  },
  {
    defaultValue: 0.3,
    key: "range",
    label: "Range",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
] as const satisfies ParameterDefinitions

const crtParams = [
  {
    defaultValue: "slot-mask",
    key: "crtMode",
    label: "Mode",
    options: [
      { label: "Slot-Mask Monitor", value: "slot-mask" },
      { label: "Aperture-Grille Monitor", value: "aperture-grille" },
      { label: "Composite TV", value: "composite-tv" },
    ],
    type: "select",
  },
  {
    defaultValue: 3,
    key: "cellSize",
    label: "Mask Scale",
    max: 32,
    min: 2,
    step: 2,
    type: "number",
  },
  {
    defaultValue: 0.17,
    key: "scanlineIntensity",
    label: "Scanline Intensity",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 1,
    key: "maskIntensity",
    label: "Mask Intensity",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.15,
    group: "Distortion",
    key: "barrelDistortion",
    label: "Barrel Distortion",
    max: 0.3,
    min: 0,
    step: 0.001,
    type: "number",
  },
  {
    defaultValue: 2,
    group: "Distortion",
    key: "chromaticAberration",
    label: "Convergence",
    max: 2,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.58,
    group: "Phosphor",
    key: "beamFocus",
    label: "Beam Focus",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 1.2,
    group: "Phosphor",
    key: "brightness",
    label: "Brightness",
    max: 100,
    min: 0.5,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 1,
    group: "Phosphor",
    key: "highlightDrive",
    label: "Highlight Drive",
    max: 100,
    min: 1,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.62,
    group: "Phosphor",
    key: "highlightThreshold",
    label: "Highlight Threshold",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.25,
    group: "Phosphor",
    key: "shoulder",
    label: "Shoulder",
    max: 4,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 1.15,
    group: "Phosphor",
    key: "chromaRetention",
    label: "Chroma Retention",
    max: 2,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.16,
    group: "Phosphor",
    key: "shadowLift",
    label: "Shadow Lift",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.18,
    group: "Phosphor",
    key: "persistence",
    label: "Persistence",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.45,
    group: "Distortion",
    key: "vignetteIntensity",
    label: "Vignette",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.2,
    group: "Noise",
    key: "flickerIntensity",
    label: "Flicker",
    max: 0.2,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.13,
    group: "Noise",
    key: "glitchIntensity",
    label: "Glitch",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 5,
    group: "Noise",
    key: "glitchSpeed",
    label: "Glitch Speed",
    max: 5,
    min: 0.1,
    step: 0.1,
    type: "number",
    visibleWhen: {
      gte: 0.01,
      key: "glitchIntensity",
    },
  },
  {
    defaultValue: 0.45,
    group: "Signal",
    key: "signalArtifacts",
    label: "Signal Artifacts",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      equals: "composite-tv",
      key: "crtMode",
    },
  },
  {
    defaultValue: true,
    group: "Bloom",
    key: "bloomEnabled",
    label: "Bloom",
    type: "boolean",
  },
  {
    defaultValue: 1.93,
    group: "Bloom",
    key: "bloomIntensity",
    label: "Intensity",
    max: 8,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "bloomEnabled",
    },
  },
  {
    defaultValue: 0,
    group: "Bloom",
    key: "bloomThreshold",
    label: "Threshold",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "bloomEnabled",
    },
  },
  {
    defaultValue: 8,
    group: "Bloom",
    key: "bloomRadius",
    label: "Radius",
    max: 24,
    min: 0,
    step: 0.25,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "bloomEnabled",
    },
  },
  {
    defaultValue: 0.31,
    group: "Bloom",
    key: "bloomSoftness",
    label: "Softness",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "bloomEnabled",
    },
  },
] as const satisfies ParameterDefinitions

const blurParams = [
  {
    defaultValue: 8,
    key: "radius",
    label: "Radius",
    max: 64,
    min: 0,
    step: 1,
    type: "number",
  },
  {
    defaultValue: 2,
    key: "passes",
    label: "Passes",
    max: 8,
    min: 1,
    step: 1,
    type: "number",
  },
] as const satisfies ParameterDefinitions

const layerDefinitions: Record<LayerType, LayerDefinition> = {
  ascii: {
    defaultName: "ASCII",
    kind: "effect",
    params: asciiParams,
    type: "ascii",
  },
  blur: {
    defaultName: "Blur",
    kind: "effect",
    params: blurParams,
    type: "blur",
  },
  crt: {
    defaultName: "CRT",
    kind: "effect",
    params: crtParams,
    type: "crt",
  },
  dithering: {
    defaultName: "Dithering",
    kind: "effect",
    params: ditheringParams,
    type: "dithering",
  },
  fluid: {
    defaultName: "Fluid",
    kind: "source",
    params: fluidParams,
    type: "fluid",
  },
  gradient: {
    defaultName: "Gradient",
    kind: "source",
    params: gradientParams,
    type: "gradient",
  },
  "custom-shader": {
    defaultName: "Custom Shader",
    kind: "source",
    params: customShaderParams,
    type: "custom-shader",
  },
  halftone: {
    defaultName: "Halftone",
    kind: "effect",
    params: halftoneParams,
    type: "halftone",
  },
  "particle-grid": {
    defaultName: "Particle Grid",
    kind: "effect",
    params: particleGridParams,
    type: "particle-grid",
  },
  image: {
    assetKind: "image",
    defaultName: "Image",
    kind: "source",
    params: imageParams,
    type: "image",
  },
  live: {
    defaultName: "Live Camera",
    kind: "source",
    params: liveParams,
    type: "live",
  },
  model: {
    assetKind: "model",
    defaultName: "3D Model",
    kind: "model",
    params: modelParams,
    type: "model",
  },
  "pixel-sorting": {
    defaultName: "Pixel Sorting",
    kind: "effect",
    params: pixelSortingParams,
    type: "pixel-sorting",
  },
  pixelation: {
    defaultName: "Pixelation",
    kind: "effect",
    params: pixelationParams,
    type: "pixelation",
  },
  video: {
    assetKind: "video",
    defaultName: "Video",
    kind: "source",
    params: videoParams,
    type: "video",
  },
}

export const DEFAULT_SOURCE_LAYER_TYPE: SourceLayerType = "gradient"
export const DEFAULT_EFFECT_LAYER_TYPE: EffectLayerType = "ascii"
export const DEFAULT_MODEL_LAYER_TYPE: ModelLayerType = "model"

export function getLayerDefinition(type: LayerType): LayerDefinition {
  return layerDefinitions[type]
}

export function getLayerDefinitions(): LayerDefinition[] {
  return Object.values(layerDefinitions)
}

export function getLayerDefinitionsByKind(kind: LayerKind): LayerDefinition[] {
  return getLayerDefinitions().filter((definition) => definition.kind === kind)
}
