import type {
  EffectLayerType,
  LayerDefinition,
  LayerKind,
  LayerType,
  ModelLayerType,
  ParameterDefinitions,
  SourceLayerType,
} from "@/features/editor/types"

const imageParams = [
  {
    defaultValue: "cover",
    key: "fitMode",
    label: "Fit",
    options: [
      { label: "Cover", value: "cover" },
      { label: "Contain", value: "contain" },
      { label: "Stretch", value: "stretch" },
    ],
    type: "select",
  },
  {
    defaultValue: 1,
    key: "scale",
    label: "Scale",
    max: 4,
    min: 0.25,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: [0, 0] as [number, number],
    key: "offset",
    label: "Offset",
    max: 1,
    min: -1,
    step: 0.01,
    type: "vec2",
  },
] as const satisfies ParameterDefinitions

const videoParams = [
  ...imageParams,
  {
    defaultValue: 1,
    key: "playbackRate",
    label: "Playback Rate",
    max: 4,
    min: 0.25,
    step: 0.05,
    type: "number",
  },
] as const satisfies ParameterDefinitions

const gradientParams = [
  {
    defaultValue: 3,
    group: "Points",
    key: "activePoints",
    label: "Active Points",
    max: 5,
    min: 2,
    step: 1,
    type: "number",
  },
  {
    defaultValue: "#0E0C0C",
    group: "Points",
    key: "point1Color",
    label: "Point 1 Color",
    type: "color",
  },
  {
    defaultValue: [-0.82, -0.62] as [number, number],
    group: "Points",
    key: "point1Position",
    label: "Point 1 Position",
    max: 1.5,
    min: -1.5,
    step: 0.01,
    type: "vec2",
  },
  {
    defaultValue: 0.42,
    group: "Points",
    key: "point1Weight",
    label: "Point 1 Weight",
    max: 3,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: "#C1FF00",
    group: "Points",
    key: "point2Color",
    label: "Point 2 Color",
    type: "color",
  },
  {
    defaultValue: [0.22, 0.72] as [number, number],
    group: "Points",
    key: "point2Position",
    label: "Point 2 Position",
    max: 1.5,
    min: -1.5,
    step: 0.01,
    type: "vec2",
  },
  {
    defaultValue: 1.55,
    group: "Points",
    key: "point2Weight",
    label: "Point 2 Weight",
    max: 3,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: "#B2DAD5",
    group: "Points",
    key: "point3Color",
    label: "Point 3 Color",
    type: "color",
    visibleWhen: {
      gte: 3,
      key: "activePoints",
    },
  },
  {
    defaultValue: [0.88, -0.26] as [number, number],
    group: "Points",
    key: "point3Position",
    label: "Point 3 Position",
    max: 1.5,
    min: -1.5,
    step: 0.01,
    type: "vec2",
    visibleWhen: {
      gte: 3,
      key: "activePoints",
    },
  },
  {
    defaultValue: 0.64,
    group: "Points",
    key: "point3Weight",
    label: "Point 3 Weight",
    max: 3,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      gte: 3,
      key: "activePoints",
    },
  },
  {
    defaultValue: "#3B4148",
    group: "Points",
    key: "point4Color",
    label: "Point 4 Color",
    type: "color",
    visibleWhen: {
      gte: 4,
      key: "activePoints",
    },
  },
  {
    defaultValue: [-0.34, 0.52] as [number, number],
    group: "Points",
    key: "point4Position",
    label: "Point 4 Position",
    max: 1.5,
    min: -1.5,
    step: 0.01,
    type: "vec2",
    visibleWhen: {
      gte: 4,
      key: "activePoints",
    },
  },
  {
    defaultValue: 0.82,
    group: "Points",
    key: "point4Weight",
    label: "Point 4 Weight",
    max: 3,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      gte: 4,
      key: "activePoints",
    },
  },
  {
    defaultValue: "#F3E7D0",
    group: "Points",
    key: "point5Color",
    label: "Point 5 Color",
    type: "color",
    visibleWhen: {
      gte: 5,
      key: "activePoints",
    },
  },
  {
    defaultValue: [0.58, -0.76] as [number, number],
    group: "Points",
    key: "point5Position",
    label: "Point 5 Position",
    max: 1.5,
    min: -1.5,
    step: 0.01,
    type: "vec2",
    visibleWhen: {
      gte: 5,
      key: "activePoints",
    },
  },
  {
    defaultValue: 0.48,
    group: "Points",
    key: "point5Weight",
    label: "Point 5 Weight",
    max: 3,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      gte: 5,
      key: "activePoints",
    },
  },
  {
    defaultValue: "simplex",
    group: "Distortion",
    key: "noiseType",
    label: "Noise",
    options: [
      { label: "Simplex", value: "simplex" },
      { label: "Turbulence", value: "turbulence" },
      { label: "Perlin", value: "perlin" },
    ],
    type: "select",
  },
  {
    defaultValue: 0.64,
    group: "Distortion",
    key: "warpAmount",
    label: "Warp Amount",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 5.56,
    group: "Distortion",
    key: "warpScale",
    label: "Warp Scale",
    max: 6,
    min: 0.1,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.69,
    group: "Distortion",
    key: "vortexAmount",
    label: "Vortex",
    max: 1,
    min: -1,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: true,
    group: "Animation",
    key: "animate",
    label: "Animate",
    type: "boolean",
  },
  {
    defaultValue: 0,
    group: "Animation",
    key: "motionAmount",
    label: "Motion Amount",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.2,
    group: "Animation",
    key: "motionSpeed",
    label: "Motion Speed",
    max: 2,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "animate",
    },
  },
  {
    defaultValue: 2.05,
    group: "Distortion",
    key: "falloff",
    label: "Falloff",
    max: 4,
    min: 0.5,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: "reinhard",
    group: "Finish",
    key: "tonemapMode",
    label: "Tonemap",
    options: [
      { label: "None", value: "none" },
      { label: "ACES", value: "aces" },
      { label: "Reinhard", value: "reinhard" },
      { label: "Toto's", value: "totos" },
      { label: "Cinematic", value: "cinematic" },
    ],
    type: "select",
  },
  {
    defaultValue: 0,
    group: "Finish",
    key: "glowStrength",
    label: "Glow Strength",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0,
    group: "Finish",
    key: "glowThreshold",
    label: "Glow Threshold",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.08,
    group: "Finish",
    key: "grainAmount",
    label: "Grain",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.12,
    group: "Finish",
    key: "vignetteStrength",
    label: "Vignette Strength",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 1.5,
    group: "Finish",
    key: "vignetteRadius",
    label: "Vignette Radius",
    max: 1.5,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 1,
    group: "Finish",
    key: "vignetteSoftness",
    label: "Vignette Softness",
    max: 1,
    min: 0.01,
    step: 0.01,
    type: "number",
  },
] as const satisfies ParameterDefinitions

const fluidParams = [
  {
    defaultValue: 24,
    key: "iterations",
    label: "Iterations",
    max: 128,
    min: 4,
    step: 1,
    type: "number",
  },
  {
    defaultValue: 0.92,
    key: "dissipation",
    label: "Dissipation",
    max: 0.999,
    min: 0.5,
    step: 0.001,
    type: "number",
  },
  {
    defaultValue: 0.24,
    key: "pressure",
    label: "Pressure",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: "#3c73ff",
    key: "inkColor",
    label: "Ink Color",
    type: "color",
  },
] as const satisfies ParameterDefinitions

const modelParams = [
  {
    defaultValue: "studio",
    key: "environment",
    label: "Environment",
    options: [
      { label: "Studio", value: "studio" },
      { label: "Sunset", value: "sunset" },
      { label: "Warehouse", value: "warehouse" },
      { label: "Night", value: "night" },
    ],
    type: "select",
  },
  {
    defaultValue: 1,
    key: "environmentStrength",
    label: "Env Strength",
    max: 2,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 1.2,
    key: "cameraDistance",
    label: "Camera Distance",
    max: 6,
    min: 0.2,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: [0, 0, 0] as [number, number, number],
    key: "cameraOrbit",
    label: "Camera Orbit",
    max: 6.283,
    min: -6.283,
    step: 0.01,
    type: "vec3",
  },
  {
    defaultValue: false,
    key: "autoRotate",
    label: "Auto Rotate",
    type: "boolean",
  },
  {
    defaultValue: 0.6,
    key: "autoRotateSpeed",
    label: "Rotate Speed",
    max: 4,
    min: -4,
    step: 0.01,
    type: "number",
  },
] as const satisfies ParameterDefinitions

const asciiParams = [
  {
    defaultValue: 12,
    key: "cellSize",
    label: "Cell Size",
    max: 48,
    min: 4,
    step: 1,
    type: "number",
  },
  {
    animatable: false,
    defaultValue: "light",
    key: "charset",
    label: "Charset",
    options: [
      { label: "Light", value: "light" },
      { label: "Dense", value: "dense" },
      { label: "Blocks", value: "blocks" },
      { label: "Hatching", value: "hatching" },
      { label: "Binary", value: "binary" },
      { label: "Custom", value: "custom" },
    ],
    type: "select",
  },
  {
    animatable: false,
    defaultValue: " .:-=+*#%@",
    key: "customChars",
    label: "Custom Chars",
    maxLength: 32,
    type: "text",
    visibleWhen: {
      equals: "custom",
      key: "charset",
    },
  },
  {
    defaultValue: "regular",
    key: "fontWeight",
    label: "Font Weight",
    options: [
      { label: "Thin", value: "thin" },
      { label: "Regular", value: "regular" },
      { label: "Bold", value: "bold" },
    ],
    type: "select",
  },
  {
    defaultValue: "monochrome",
    key: "colorMode",
    label: "Color Mode",
    options: [
      { label: "Source", value: "source" },
      { label: "Monochrome", value: "monochrome" },
      // { label: "Green Terminal", value: "green-terminal" },
    ],
    type: "select",
  },
  {
    defaultValue: "#f5f5f0",
    key: "monoColor",
    label: "Tint",
    type: "color",
    visibleWhen: {
      equals: "monochrome",
      key: "colorMode",
    },
  },
  {
    defaultValue: 0,
    key: "bgOpacity",
    label: "Background",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      equals: "source",
      key: "colorMode",
    },
  },
  {
    defaultValue: false,
    key: "invert",
    label: "Invert",
    type: "boolean",
  },
  {
    defaultValue: false,
    group: "Bloom",
    key: "bloomEnabled",
    label: "Bloom",
    type: "boolean",
  },
  {
    defaultValue: 1.25,
    group: "Bloom",
    key: "bloomIntensity",
    label: "Intensity",
    max: 8,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "bloomEnabled",
    },
  },
  {
    defaultValue: 0.6,
    group: "Bloom",
    key: "bloomThreshold",
    label: "Threshold",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "bloomEnabled",
    },
  },
  {
    defaultValue: 6,
    group: "Bloom",
    key: "bloomRadius",
    label: "Radius",
    max: 24,
    min: 0,
    step: 0.25,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "bloomEnabled",
    },
  },
  {
    defaultValue: 0.35,
    group: "Bloom",
    key: "bloomSoftness",
    label: "Softness",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "bloomEnabled",
    },
  },
] as const satisfies ParameterDefinitions

const ditheringParams = [
  {
    defaultValue: "custom",
    group: "Pattern",
    key: "preset",
    label: "Preset",
    options: [
      { label: "Custom", value: "custom" },
      { label: "Game Boy", value: "gameboy" },
    ],
    type: "select",
  },
  {
    defaultValue: "bayer-4x4",
    group: "Pattern",
    key: "algorithm",
    label: "Algorithm",
    options: [
      { label: "Bayer 2x2", value: "bayer-2x2" },
      { label: "Bayer 4x4", value: "bayer-4x4" },
      { label: "Bayer 8x8", value: "bayer-8x8" },
      { label: "Noise", value: "noise" },
    ],
    type: "select",
  },
  {
    defaultValue: "source",
    group: "Color",
    key: "colorMode",
    label: "Color Mode",
    options: [
      { label: "Monochrome", value: "monochrome" },
      { label: "Source Color", value: "source" },
      { label: "Duo Tone", value: "duo-tone" },
    ],
    type: "select",
  },
  {
    defaultValue: "#f5f5f0",
    group: "Color",
    key: "monoColor",
    label: "Color",
    type: "color",
    visibleWhen: {
      equals: "monochrome",
      key: "colorMode",
    },
  },
  {
    defaultValue: "#101010",
    group: "Color",
    key: "shadowColor",
    label: "Shadow",
    type: "color",
    visibleWhen: {
      equals: "duo-tone",
      key: "colorMode",
    },
  },
  {
    defaultValue: "#f5f2e8",
    group: "Color",
    key: "highlightColor",
    label: "Highlight",
    type: "color",
    visibleWhen: {
      equals: "duo-tone",
      key: "colorMode",
    },
  },
  {
    defaultValue: 1,
    group: "Pattern",
    key: "pixelSize",
    label: "Pixel Size",
    max: 24,
    min: 1,
    step: 1,
    type: "number",
  },
  {
    defaultValue: 0.5,
    group: "Pattern",
    key: "spread",
    label: "Strength",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 4,
    group: "Color",
    key: "levels",
    label: "Levels",
    max: 16,
    min: 2,
    step: 1,
    type: "number",
  },
] as const satisfies ParameterDefinitions

const halftoneParams = [
  {
    defaultValue: "circle",
    key: "shape",
    label: "Shape",
    options: [
      { label: "Circle", value: "circle" },
      { label: "Square", value: "square" },
      { label: "Diamond", value: "diamond" },
      { label: "Line", value: "line" },
    ],
    type: "select",
  },
  {
    defaultValue: 12,
    key: "spacing",
    label: "Spacing",
    max: 48,
    min: 2,
    step: 1,
    type: "number",
  },
  {
    defaultValue: 28,
    key: "angle",
    label: "Angle",
    max: 360,
    min: 0,
    step: 1,
    type: "number",
  },
  {
    defaultValue: 1,
    key: "contrast",
    label: "Contrast",
    max: 2,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.25,
    key: "softness",
    label: "Softness",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: "#0d1014",
    key: "ink",
    label: "Ink",
    type: "color",
  },
] as const satisfies ParameterDefinitions

const pixelationParams = [
  {
    defaultValue: 8,
    key: "cellSize",
    label: "Cell Size",
    max: 64,
    min: 2,
    step: 1,
    type: "number",
  },
  {
    defaultValue: "square",
    key: "shape",
    label: "Shape",
    options: [
      { label: "Square", value: "square" },
      { label: "Circle", value: "circle" },
      { label: "Diamond", value: "diamond" },
    ],
    type: "select",
  },
] as const satisfies ParameterDefinitions

const pixelSortingParams = [
  {
    defaultValue: 0.55,
    key: "threshold",
    label: "Threshold",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: "horizontal",
    key: "direction",
    label: "Direction",
    options: [
      { label: "Horizontal", value: "horizontal" },
      { label: "Vertical", value: "vertical" },
    ],
    type: "select",
  },
  {
    defaultValue: "luma",
    key: "mode",
    label: "Mode",
    options: [
      { label: "Luma", value: "luma" },
      { label: "Hue", value: "hue" },
      { label: "Saturation", value: "saturation" },
    ],
    type: "select",
  },
  {
    defaultValue: 0.5,
    key: "range",
    label: "Range",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
] as const satisfies ParameterDefinitions

const blurParams = [
  {
    defaultValue: 8,
    key: "radius",
    label: "Radius",
    max: 64,
    min: 0,
    step: 1,
    type: "number",
  },
  {
    defaultValue: 2,
    key: "passes",
    label: "Passes",
    max: 8,
    min: 1,
    step: 1,
    type: "number",
  },
] as const satisfies ParameterDefinitions

const layerDefinitions: Record<LayerType, LayerDefinition> = {
  ascii: {
    defaultName: "ASCII",
    kind: "effect",
    params: asciiParams,
    type: "ascii",
  },
  blur: {
    defaultName: "Blur",
    kind: "effect",
    params: blurParams,
    type: "blur",
  },
  dithering: {
    defaultName: "Dithering",
    kind: "effect",
    params: ditheringParams,
    type: "dithering",
  },
  fluid: {
    defaultName: "Fluid",
    kind: "source",
    params: fluidParams,
    type: "fluid",
  },
  gradient: {
    defaultName: "Gradient",
    kind: "source",
    params: gradientParams,
    type: "gradient",
  },
  halftone: {
    defaultName: "Halftone",
    kind: "effect",
    params: halftoneParams,
    type: "halftone",
  },
  image: {
    assetKind: "image",
    defaultName: "Image",
    kind: "source",
    params: imageParams,
    type: "image",
  },
  model: {
    assetKind: "model",
    defaultName: "3D Model",
    kind: "model",
    params: modelParams,
    type: "model",
  },
  "pixel-sorting": {
    defaultName: "Pixel Sorting",
    kind: "effect",
    params: pixelSortingParams,
    type: "pixel-sorting",
  },
  pixelation: {
    defaultName: "Pixelation",
    kind: "effect",
    params: pixelationParams,
    type: "pixelation",
  },
  video: {
    assetKind: "video",
    defaultName: "Video",
    kind: "source",
    params: videoParams,
    type: "video",
  },
}

export const DEFAULT_SOURCE_LAYER_TYPE: SourceLayerType = "gradient"
export const DEFAULT_EFFECT_LAYER_TYPE: EffectLayerType = "ascii"
export const DEFAULT_MODEL_LAYER_TYPE: ModelLayerType = "model"

export function getLayerDefinition(type: LayerType): LayerDefinition {
  return layerDefinitions[type]
}

export function getLayerDefinitions(): LayerDefinition[] {
  return Object.values(layerDefinitions)
}

export function getLayerDefinitionsByKind(kind: LayerKind): LayerDefinition[] {
  return getLayerDefinitions().filter((definition) => definition.kind === kind)
}
